import {
   Clapperboard,
   Compass,
   Sparkles,
   Laugh,
   Shield,
   BookOpen,
   Drama,
   Users,
   Wand,
   Landmark,
   Ghost,
   Music,
   Search,
   Heart,
   Rocket,
   Tv,
   Flame,
   Swords,
   Mountain
} from "lucide-react";

export const genres = [
   { id: 28, name: "Action", icon: Flame },
   { id: 12, name: "Adventure", icon: Compass },
   { id: 16, name: "Animation", icon: Sparkles },
   { id: 35, name: "Comedy", icon: Laugh },
   { id: 80, name: "Crime", icon: Shield },
   { id: 99, name: "Documentary", icon: BookOpen },
   { id: 18, name: "Drama", icon: Drama },
   { id: 10751, name: "Family", icon: Users },
   { id: 14, name: "Fantasy", icon: Wand },
   { id: 36, name: "History", icon: Landmark },
   { id: 27, name: "Horror", icon: Ghost },
   { id: 10402, name: "Music", icon: Music },
   { id: 9648, name: "Mystery", icon: Search },
   { id: 10749, name: "Romance", icon: Heart },
   { id: 878, name: "Science Fiction", icon: Rocket },
   { id: 10770, name: "TV Movie", icon: Tv },
   { id: 53, name: "Thriller", icon: Swords },
   { id: 10752, name: "War", icon: Swords },
   { id: 37, name: "Western", icon: Mountain }
];